name: Release
on:
  workflow_dispatch: # manual release

jobs:
  npm:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false # Needed so that semantic release can use the admin token

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.4

      - name: Release library test1
        run: npx ng run test1:release
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Personal access token with repo permissions

      - name: Release library test2
        run: npx ng run test2:release
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Personal access token with repo permissions
